# Generated by Django 2.0.1 on 2018-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='wizzeruser',
            name='second_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='wizzeruser',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
