# Generated by Django 2.0.1 on 2018-03-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_auto_20180302_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('whiz_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.WizzerUser')),
            ],
        ),
    ]
