# Generated by Django 2.0.1 on 2018-03-11 06:22

import SocialMedia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_wizzeruser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizzeruser',
            name='background_image',
            field=models.FileField(default='', upload_to=SocialMedia.models.background_image_path),
        ),
        migrations.AlterField(
            model_name='whiz',
            name='whiz_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.WizzerUser'),
        ),
    ]
