# Generated by Django 2.0.1 on 2018-03-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_whiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiz',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
