# Generated by Django 2.0.1 on 2018-03-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_auto_20180313_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='disliked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMedia.WizzerUser'),
        ),
    ]
