# Generated by Django 2.0.1 on 2018-03-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0004_whiz_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiz',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
    ]
