# Generated by Django 2.0.1 on 2018-03-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0004_auto_20180313_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizzeruser',
            name='following',
        ),
        migrations.AddField(
            model_name='wizzeruser',
            name='following',
            field=models.ManyToManyField(to='SocialMedia.WizzerUser'),
        ),
    ]
