# Generated by Django 2.0.1 on 2018-03-11 09:42

import SocialMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_auto_20180311_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='background_image',
            field=models.FileField(default='madefault\\default-background.jpg', upload_to=SocialMedia.models.background_image_path),
        ),
        migrations.AlterField(
            model_name='wizzeruser',
            name='profile_picture',
            field=models.FileField(default='default\\default-profile-picture.jpg', upload_to=SocialMedia.models.profile_picture_path),
        ),
    ]
