# Generated by Django 2.0.1 on 2018-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_auto_20180313_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='following',
            field=models.ManyToManyField(to='SocialMedia.WizzerUser'),
        ),
    ]
