# Generated by Django 2.0.1 on 2018-03-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0007_auto_20180302_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizzeruser',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wizzeruser',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
