# Generated by Django 2.0.1 on 2018-03-11 09:43

import SocialMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0007_auto_20180311_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='background_image',
            field=models.FileField(default='default\\default-background.jpg', upload_to=SocialMedia.models.background_image_path),
        ),
    ]
