# Generated by Django 2.0.1 on 2018-03-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_auto_20180303_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizzeruser',
            name='profile_picture',
            field=models.FileField(default='', upload_to=None),
        ),
    ]
