# Generated by Django 2.0.1 on 2018-03-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_auto_20180313_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_wizzeruser_followers_+', to='SocialMedia.WizzerUser'),
        ),
        migrations.AlterField(
            model_name='wizzeruser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_wizzeruser_following_+', to='SocialMedia.WizzerUser'),
        ),
    ]
