# Generated by Django 2.0.1 on 2018-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_auto_20180313_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower_set', to='SocialMedia.WizzerUser'),
        ),
        migrations.AlterField(
            model_name='wizzeruser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_set', to='SocialMedia.WizzerUser'),
        ),
    ]
