# Generated by Django 2.0.1 on 2018-03-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0010_auto_20180307_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='profile_picture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
