# Generated by Django 2.0.1 on 2018-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0010_auto_20180313_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='whiz',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='like',
            name='whiz',
        ),
        migrations.AddField(
            model_name='whiz',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislike_set', to='SocialMedia.WizzerUser'),
        ),
        migrations.AddField(
            model_name='whiz',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_set', to='SocialMedia.WizzerUser'),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
