# Generated by Django 2.0.1 on 2018-03-08 05:44

import SocialMedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0011_auto_20180307_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzeruser',
            name='profile_picture',
            field=models.FileField(default='', upload_to=SocialMedia.models.user_directory_path),
        ),
    ]
